-- Noms vernaculaires des espèces — données saisies manuellement
-- À jouer après 001_initial_schema.sql

UPDATE species SET common_name_fr = 'Baleine boréale', common_name_en = 'Bowhead Whale' WHERE scientific_name = 'Balaena mysticetus';
UPDATE species SET common_name_fr = 'Baleine de Minke', common_name_en = 'Common Minke Whale' WHERE scientific_name = 'Balaenoptera acutorostrata';
UPDATE species SET common_name_fr = 'Petit rorqual de l''Antarctique', common_name_en = 'Antarctic Minke Whale' WHERE scientific_name = 'Balaenoptera bonaerensis';
UPDATE species SET common_name_fr = 'Rorqual boréal', common_name_en = 'Sei Whale' WHERE scientific_name = 'Balaenoptera borealis';
UPDATE species SET common_name_fr = 'Rorqual de Bryde', common_name_en = 'Bryde''s Whale' WHERE scientific_name = 'Balaenoptera edeni';
UPDATE species SET common_name_fr = 'Baleine bleue', common_name_en = 'Blue Whale' WHERE scientific_name = 'Balaenoptera musculus';
UPDATE species SET common_name_fr = 'Rorqual d''Omura', common_name_en = 'Omura’s Whale' WHERE scientific_name = 'Balaenoptera omurai';
UPDATE species SET common_name_fr = 'Rorqual commun', common_name_en = 'Fin Whale' WHERE scientific_name = 'Balaenoptera physalus';
UPDATE species SET common_name_fr = 'Rorqual de Rice', common_name_en = 'Rice''s Whale' WHERE scientific_name = 'Balaenoptera ricei';
UPDATE species SET common_name_fr = 'Bérardie d''Arnoux', common_name_en = 'Arnoux''s Beaked Whale' WHERE scientific_name = 'Berardius arnuxii';
UPDATE species SET common_name_fr = 'Bérardie de Baird', common_name_en = 'Baird''s Beaked Whale' WHERE scientific_name = 'Berardius bairdii';
UPDATE species SET common_name_fr = 'Berardius minimus', common_name_en = 'Sato’s Beaked Whale' WHERE scientific_name = 'Berardius minimus';
UPDATE species SET common_name_fr = 'Baleine pygmée', common_name_en = 'Pygmy Right Whale' WHERE scientific_name = 'Caperea marginata';
UPDATE species SET common_name_fr = 'Dauphin de Commerson', common_name_en = 'Commerson''s Dolphin' WHERE scientific_name = 'Cephalorhynchus commersonii';
UPDATE species SET common_name_fr = 'Dauphin du Chili', common_name_en = 'Chilean Dolphin' WHERE scientific_name = 'Cephalorhynchus eutropia';
UPDATE species SET common_name_fr = 'Dauphin du Cap', common_name_en = 'Heaviside''s Dolphin' WHERE scientific_name = 'Cephalorhynchus heavisidii';
UPDATE species SET common_name_fr = 'Dauphin d''Hector', common_name_en = 'Hector''s Dolphin' WHERE scientific_name = 'Cephalorhynchus hectori';
UPDATE species SET common_name_fr = 'Béluga', common_name_en = 'Beluga Whale' WHERE scientific_name = 'Delphinapterus leucas';
UPDATE species SET common_name_fr = 'Dauphin commun à bec court', common_name_en = 'Common Dolphin' WHERE scientific_name = 'Delphinus delphis';
UPDATE species SET common_name_fr = 'Marsouin aptère du Yangtsé', common_name_en = 'Yangtze finless porpoise' WHERE scientific_name = 'Neophocaena asiaeorientalis';
UPDATE species SET common_name_fr = 'Baleine grise', common_name_en = 'Gray Whale' WHERE scientific_name = 'Eschrichtius robustus';
UPDATE species SET common_name_fr = 'Baleine franche australe', common_name_en = 'Southern Right Whale' WHERE scientific_name = 'Eubalaena australis';
UPDATE species SET common_name_fr = 'Baleine franche de l''Atlantique nord', common_name_en = 'North Atlantic Right Whale' WHERE scientific_name = 'Eubalaena glacialis';
UPDATE species SET common_name_fr = 'Baleine franche du Pacifique Nord', common_name_en = 'North Pacific Right Whale' WHERE scientific_name = 'Eubalaena japonica';
UPDATE species SET common_name_fr = 'Orque pygmée', common_name_en = 'Pygmy Killer Whale' WHERE scientific_name = 'Feresa attenuata';
UPDATE species SET common_name_fr = 'Globicéphale tropical', common_name_en = 'Short-finned Pilot Whale' WHERE scientific_name = 'Globicephala macrorhynchus';
UPDATE species SET common_name_fr = 'Globicephala melas', common_name_en = 'Long-finned Pilot Whale' WHERE scientific_name = 'Globicephala melas';
UPDATE species SET common_name_fr = 'Dauphin de Risso', common_name_en = 'Risso''s Dolphin' WHERE scientific_name = 'Grampus griseus';
UPDATE species SET common_name_fr = 'Hypéroodon arctique', common_name_en = 'Northern Bottlenose Whale' WHERE scientific_name = 'Hyperoodon ampullatus';
UPDATE species SET common_name_fr = 'Hypéroodon antarctique', common_name_en = 'Southern Bottlenose Whale' WHERE scientific_name = 'Hyperoodon planifrons';
UPDATE species SET common_name_fr = 'Baleine à bec de Longman', common_name_en = 'Indo-Pacific Beaked Whale' WHERE scientific_name = 'Indopacetus pacificus';
UPDATE species SET common_name_fr = 'Cachalot pygmée', common_name_en = 'Pygmy Sperm Whale' WHERE scientific_name = 'Kogia breviceps';
UPDATE species SET common_name_fr = 'Cachalot nain', common_name_en = 'Dwarf Sperm Whale' WHERE scientific_name = 'Kogia sima';
UPDATE species SET common_name_fr = 'Dauphin de Fraser', common_name_en = 'Fraser''s Dolphin' WHERE scientific_name = 'Lagenodelphis hosei';
UPDATE species SET common_name_fr = 'Dauphin à nez blanc', common_name_en = 'White-beaked Dolphin' WHERE scientific_name = 'Lagenorhynchus albirostris';
UPDATE species SET common_name_fr = 'Dauphin obscur', common_name_en = 'Dusky Dolphin' WHERE scientific_name = 'Lagenorhynchus obscurus';
UPDATE species SET common_name_fr = 'Dauphin du Nord', common_name_en = 'Northern Right Whale Dolphin' WHERE scientific_name = 'Lissodelphis borealis';
UPDATE species SET common_name_fr = 'Dauphin aptère austral', common_name_en = 'Southern Right Whale Dolphin' WHERE scientific_name = 'Lissodelphis peronii';
UPDATE species SET common_name_fr = 'Baleine à bosse', common_name_en = 'Humpback Whale' WHERE scientific_name = 'Megaptera novaeangliae';
UPDATE species SET common_name_fr = 'Baleine à bec de Sowerby', common_name_en = 'Sowerby''s Beaked Whale' WHERE scientific_name = 'Mesoplodon bidens';
UPDATE species SET common_name_fr = 'Baleine à bec d''Andrews', common_name_en = 'Andrew''s Beaked Whale' WHERE scientific_name = 'Mesoplodon bowdoini';
UPDATE species SET common_name_fr = 'Baleine à bec de Hubbs', common_name_en = 'Hubbs'' Beaked Whale' WHERE scientific_name = 'Mesoplodon carlhubbsi';
UPDATE species SET common_name_fr = 'Baleine à bec de Blainville', common_name_en = 'Blainville''s Beaked Whale' WHERE scientific_name = 'Mesoplodon densirostris';
UPDATE species SET common_name_fr = 'Baleine à bec de Ramari', common_name_en = 'Ramari''s Beaked Whale' WHERE scientific_name = 'Mesoplodon eueu';
UPDATE species SET common_name_fr = 'Baleine à bec de Gervais', common_name_en = 'Gervais'' Beaked Whale' WHERE scientific_name = 'Mesoplodon europaeus';
UPDATE species SET common_name_fr = 'Mésoplodon japonais', common_name_en = 'Ginkgo-toothed Beaked Whale' WHERE scientific_name = 'Mesoplodon ginkgodens';
UPDATE species SET common_name_fr = 'Baleine à bec de Gray', common_name_en = 'Gray''s Beaked Whale' WHERE scientific_name = 'Mesoplodon grayi';
UPDATE species SET common_name_fr = 'Baleine à bec d''Hector', common_name_en = 'Hector''s Beaked Whale' WHERE scientific_name = 'Mesoplodon hectori';
UPDATE species SET common_name_fr = 'Baleine à bec de Deraniyagala', common_name_en = 'Deraniyagala''s Beaked Whale' WHERE scientific_name = 'Mesoplodon hotaula';
UPDATE species SET common_name_fr = 'Baleine à bec de Layard', common_name_en = 'Strap-toothed Whale' WHERE scientific_name = 'Mesoplodon layardii';
UPDATE species SET common_name_fr = 'Baleine à bec de True', common_name_en = 'True''s Beaked Whale' WHERE scientific_name = 'Mesoplodon mirus';
UPDATE species SET common_name_fr = 'Baleine à bec de Perrin', common_name_en = 'Perrin''s Beaked Whale' WHERE scientific_name = 'Mesoplodon perrini';
UPDATE species SET common_name_fr = 'Baleine à bec pygmée', common_name_en = 'Pygmy Beaked Whale' WHERE scientific_name = 'Mesoplodon peruvianus';
UPDATE species SET common_name_fr = 'Baleine à bec de Stejneger', common_name_en = 'Stejneger''s Beaked Whale' WHERE scientific_name = 'Mesoplodon stejnegeri';
UPDATE species SET common_name_fr = 'Baleine à bec de Travers', common_name_en = 'Spade-toothed Whale' WHERE scientific_name = 'Mesoplodon traversii';
UPDATE species SET common_name_fr = 'Narval', common_name_en = 'Narwhal' WHERE scientific_name = 'Monodon monoceros';
UPDATE species SET common_name_fr = 'Le marsouin aptère du Yangtsé', common_name_en = 'Yangtze finless porpoise' WHERE scientific_name = 'Neophocaena asiaeorientalisa';
UPDATE species SET common_name_fr = 'Marsouin aptère', common_name_en = 'Indo-Pacific Finless Porpoise' WHERE scientific_name = 'Neophocaena phocaenoides';
UPDATE species SET common_name_fr = 'Dauphin de l''Irrawaddy', common_name_en = 'Irrawaddy Dolphin' WHERE scientific_name = 'Orcaella brevirostris';
UPDATE species SET common_name_fr = 'Dauphin à aileron retroussé d''Australie', common_name_en = 'Australian Snubfin Dolphin' WHERE scientific_name = 'Orcaella heinsohni';
UPDATE species SET common_name_fr = 'Orque', common_name_en = 'Killer Whale' WHERE scientific_name = 'Orcinus orca';
UPDATE species SET common_name_fr = 'Dauphin d''Électre', common_name_en = 'Melon-headed Whale' WHERE scientific_name = 'Peponocephala electra';
UPDATE species SET common_name_fr = 'Marsouin à lunettes', common_name_en = 'Spectacled Porpoise' WHERE scientific_name = 'Phocoena dioptrica';
UPDATE species SET common_name_fr = 'Marsouin commun', common_name_en = 'Harbor Porpoise' WHERE scientific_name = 'Phocoena phocoena';
UPDATE species SET common_name_fr = 'Marsouin du Pacifique', common_name_en = 'Vaquita' WHERE scientific_name = 'Phocoena sinus';
UPDATE species SET common_name_fr = 'Marsouin de Burmeister', common_name_en = 'Burmeister''s Porpoise' WHERE scientific_name = 'Phocoena spinipinnis';
UPDATE species SET common_name_fr = 'Marsouin de Dall', common_name_en = 'Dall''s Porpoise' WHERE scientific_name = 'Phocoenoides dalli';
UPDATE species SET common_name_fr = 'Cachalot', common_name_en = 'Sperm Whale' WHERE scientific_name = 'Physeter macrocephalus';
UPDATE species SET common_name_fr = 'Dauphin de la Plata', common_name_en = 'La Plata dolphin' WHERE scientific_name = 'Pontoporia blainvillei';
UPDATE species SET common_name_fr = 'Fausse orque', common_name_en = 'False Killer Whale' WHERE scientific_name = 'Pseudorca crassidens';
UPDATE species SET common_name_fr = 'Dauphin de Guyane', common_name_en = 'Guiana Dolphin' WHERE scientific_name = 'Sotalia guianensis';
UPDATE species SET common_name_fr = 'Dauphin blanc de Chine', common_name_en = 'Indo-Pacific Humpback Dolphin' WHERE scientific_name = 'Sousa chinensis';
UPDATE species SET common_name_fr = 'Dauphin à bosse de l''océan Indien', common_name_en = 'Indian Ocean Humpback Dolphin' WHERE scientific_name = 'Sousa plumbea';
UPDATE species SET common_name_fr = 'Dauphin à bosse de l’Indo-Pacifique', common_name_en = 'Australian Humpback Dolphin' WHERE scientific_name = 'Sousa sahulensis';
UPDATE species SET common_name_fr = 'Dauphin à bosse de l''Atlantique', common_name_en = 'Atlantic Humpback Dolphin' WHERE scientific_name = 'Sousa teuszii';
UPDATE species SET common_name_fr = 'Dauphin tacheté pantropical', common_name_en = 'Pantropical Spotted Dolphin' WHERE scientific_name = 'Stenella attenuata';
UPDATE species SET common_name_fr = 'Dauphin clymène', common_name_en = 'Clymene Dolphin' WHERE scientific_name = 'Stenella clymene';
UPDATE species SET common_name_fr = 'Dauphin bleu et blanc', common_name_en = 'Striped Dolphin' WHERE scientific_name = 'Stenella coeruleoalba';
UPDATE species SET common_name_fr = 'Dauphin tacheté de l''Atlantique', common_name_en = 'Atlantic Spotted Dolphin' WHERE scientific_name = 'Stenella frontalis';
UPDATE species SET common_name_fr = 'Dauphin à long bec', common_name_en = 'Spinner Dolphin' WHERE scientific_name = 'Stenella longirostris';
UPDATE species SET common_name_fr = 'Dauphin à bec étroit', common_name_en = 'Rough-toothed Dolphin' WHERE scientific_name = 'Steno bredanensis';
UPDATE species SET common_name_fr = 'Tasmacète de Shepherd', common_name_en = 'Shepherd''s Beaked Whale' WHERE scientific_name = 'Tasmacetus shepherdi';
UPDATE species SET common_name_fr = 'Grand dauphin de l''océan Indien', common_name_en = 'Indo-Pacific Bottlenose Dolphin' WHERE scientific_name = 'Tursiops aduncus';
UPDATE species SET common_name_fr = 'Dauphin Burrunan', common_name_en = 'Burrunan dolphin' WHERE scientific_name = 'Tursiops australis';
UPDATE species SET common_name_fr = 'Le grand dauphin de Tamanend', common_name_en = 'Tamanend''s bottlenose dolphin' WHERE scientific_name = 'Tursiops erebennus';
UPDATE species SET common_name_fr = 'Grand dauphin', common_name_en = 'Common Bottlenose Dolphin' WHERE scientific_name = 'Tursiops truncatus';
UPDATE species SET common_name_fr = 'Baleine de Cuvier', common_name_en = 'Cuvier''s Beaked Whale' WHERE scientific_name = 'Ziphius cavirostris';